---
- name: Create the weechat relay ssh user
  user:
    name: weechat
    comment: "Weechat Relay"
    groups:
    generate_ssh_key: no

- name: Add our pubkeys
  authorized_key:
    user: weechat
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDN200GRN6YA2pGgg1laQ97ijYBL9LZy+5NqiJXV3mRi/+1HsALfZ7TIuTq7PIFD8SGnDt6P+pc8em8Qc0qsKNUmE02iM3QXzoA32EJRcaWRez00ZnyjnFbrCaXLTFloe8qYjQgLBy3cu8rLgyuvxqSTf7G0OW3mqGtXVxwMuACUh7HreusBlvQU8yWuH66mo5d9FGrO1CVIlYftZ1PJOhlWaalB7FUZ+UDhgXmNh5+me32R8kjwo8/x9uKaxRUTayWVaczf/2VBtjx37mxUbEGNjDErbzwjRgqNFYmZntbi83EWWSjERtdTGhcHACYmf8oa3Tn5KvBFc+ZFC3DWQ7zRX+wDFiwKIZVRYK2SrJRYRtrY30LoJqz4NSXspxLaHYmpB239yydZaO8g1tzebvAeoAen7wNICxOYm3hYdm29vJRgbVd775Cp70tR19CALkSR4rzuuA7YWTETpcGTcuOaSaQ24a3wBOAPs6923G7mFhMR8sYhNu99XvRsceXvQHIP6v1ydR2SJzRpY2QC4u6W2GZ2lHE4R25wNIDuuluPDPpqeOfA2S0Mn1qwLzGYmgTy91MOnpWzjI7GWPIQmLgvIjX3N/pKDNQUL++33xm5axqEzHQv6PM8S4gw8uOmiwzQ7mAq573YfoSxqLWL6ytQoy2mFQ6BKTaneSbTxSUDQ== weechat"
    key_options: 'no-pty,command="/bin/false",permitopen="localhost:{{ weechat_relay_port }}"'
