---
- name: Comment out devpts fstab entry
  become: yes
  become_user: root
  replace:
    dest: /etc/fstab
    regexp: '^devpts'
    replace: '#devpts'

- name: Fix screen run directory permissions
  become: yes
  become_user: root
  file:
    path: /var/run/screen
    mode: 0755
