---
- name: Fix screen binary permissions
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    mode: "u=rws,g=rws,o=rx"
  with_items:
    - /usr/bin/screen
    - /usr/bin/mosh
    - /usr/bin/mosh-client
    - /usr/bin/mosh-server

- name: Fix screen run directory permissions
  become: yes
  become_user: root
  file:
    path: /var/run/screen
    mode: 0755
