---
- name: create weechat conf dir
  file:
    path: /home/slava/.weechat_work
    owner: slava
    group: slava
    state: directory

- name: install weechat irc config
  template:
    src: "{{ role_path }}/files/irc.conf.j2"
    dest: "/home/slava/.weechat_work/irc.conf"
    owner: slava
    group: slava

- name: install the rest of weechat configs
  copy:
    src: "{{ item }}"
    dest: /home/slava/.weechat_work/
    owner: slava
    group: slava
  with_fileglob:
    - "{{ role_path }}/files/*conf"

- name: install the rest of weechat conf dirs
  copy:
    src: "{{ item }}"
    dest: /home/slava/.weechat_work/
    owner: slava
    group: slava
  with_items:
    - "{{ role_path }}/files/perl"
    - "{{ role_path }}/files/python"
    - "{{ role_path }}/files/script"

- name: install wee_slack
  get_url:
    url: https://raw.githubusercontent.com/wee-slack/wee-slack/master/wee_slack.py
    dest: /home/slava/.weechat_work/python/autoload/wee_slack.py

- name: run weechat_work in a screen
  shell: "(! (ps -ef | grep -q weechat_work | grep -v grep) && (screen -ls | grep pizzadough) ) && (screen -S pizzadough -X screen -t workchat -dm weechat -d /home/slava/.weechat_work) || (screen -S pizzadough -t workchat -A -d -m weechat -d /home/slava/.weechat_work)"
