---
- name: install the beloved dotfiles
  when: ansible_distribution == "CentOS" or ansible_distribution == "Debian"
  copy:
    src: "{{ item }}"
    dest: '/home/slava/'
    owner: slava
    group: slava
  with_items:
    - "{{ role_path }}/files/*"
    - "{{ role_path }}/files/.*"
    - "{{ role_path }}/files/.ssh/"

- name: install the beloved dotfiles
  when: ansible_distribution == "MacOSX"
  copy:
    src: "{{ item }}"
    dest: '/Users/slava'
    owner: slava
    group: staff
  with_items:
    - "{{ role_path }}/files/*"
    - "{{ role_path }}/files/.*"
    - "{{ role_path }}/files/.ssh/"
