---
- name: install firewalld
  yum:
    name: firewalld
    state: latest

- name: provide plex service file
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /etc/firewalld/services/
  with_items:
    - plex.xml
    - mosh.xml

- name: enable and start firewalld
  service:
    name: firewalld
    enabled: true
    state: started

- name: set firewalld interface on public zone
  firewalld:
    zone: public
    interface: eth0
    permanent: true
    state: enabled

- name: open firewall ports
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - ssh
    - mosh
